### PR TITLE
WIP: optimize codes and event selection

### PR DESCRIPTION
**Pull request by konglingteng97**

### CODE REVIEW

**Comment by rkiuchi** [comment]
Does  python/gen_table.py be used now ?

**Comment by konglingteng97** [comment]
Yes, I use it to generate some table, but it’s no use now cause I have got the table

Best regards, 
Lingteng

**Comment by rkiuchi** [comment]
I see. Why I found is that it seems it is not included in submit.sh. If it is,  you can further update submit.sh to "activate" this gen_table.py ( ... or just remove it (though it would help the other people in future) )

**Comment by konglingteng97** [comment]
OK, I will update several days later and add some new features include this one,  maybe you could merge then.

Best regards, 
Lingteng

**Comment by xshi** [comment]
@konglingteng97 If you think this PR is ready to be merged. Could you remove the "WIP" from the title and then inform @rkiuchi to merge? Thanks

**Comment by konglingteng97** [comment]
OK

Best regards, 
Lingteng

**Pull request merged**
