### PR TITLE
Merge 2 channels

### PR DESCRIPTION
**Pull request by YonsiG**
merge two branches together (with regret... in one time)

### CODE REVIEW

**Comment by xshi** [comment]
Please remove these files from git: 

A MarlinFastJet-00-02/lib/libMarlinFastJet.so (1)
A MarlinFastJet-00-02/lib/libMarlinFastJet.so.0.2 (1)
A MarlinFastJet-00-02/lib/libMarlinFastJet.so.0.2.0 (0) 

M MarlinFastJet-00-02/src/FastJetProcessor.cpp~ (0)

All files under the "build" directory: 

A build/CMakeCache.txt (556)
A build/CMakeFiles/CMakeCCompiler.cmake (49)
A build/CMakeFiles/CMakeCXXCompiler.cmake (50)
A build/CMakeFiles/CMakeDetermineCompilerABI_C.bin (0)
A build/CMakeFiles/CMakeDetermineCompilerABI_CXX.bin (0)
A build/CMakeFiles/CMakeDirectoryInformation.cmake (39)
A build/CMakeFiles/CMakeOutput.log (239)
A build/CMakeFiles/CMakeRuleHashes.txt (30)
A build/CMakeFiles/CMakeSystem.cmake (15)
A build/CMakeFiles/CompilerIdC/CMakeCCompilerId.c (229)
A build/CMakeFiles/CompilerIdC/a.out (0)
A build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp (215)
A build/CMakeFiles/CompilerIdCXX/a.out (0)
A build/CMakeFiles/Continuous.dir/DependInfo.cmake (13)
A build/CMakeFiles/Continuous.dir/build.make (63)
A build/CMakeFiles/Continuous.dir/cmake_clean.cmake (8)
A build/CMakeFiles/Continuous.dir/progress.make (1)
A build/CMakeFiles/ContinuousBuild.dir/DependInfo.cmake (13)
A build/CMakeFiles/ContinuousBuild.dir/build.make (63)
A build/CMakeFiles/ContinuousBuild.dir/cmake_clean.cmake (8)
A build/CMakeFiles/ContinuousBuild.dir/progress.make (1)
A build/CMakeFiles/ContinuousConfigure.dir/DependInfo.cmake (13)
A build/CMakeFiles/ContinuousConfigure.dir/build.make (63)
A build/CMakeFiles/ContinuousConfigure.dir/cmake_clean.cmake (8)
A build/CMakeFiles/ContinuousConfigure.dir/progress.make (1)
A build/CMakeFiles/ContinuousCoverage.dir/DependInfo.cmake (13)
A build/CMakeFiles/ContinuousCoverage.dir/build.make (63)
A build/CMakeFiles/ContinuousCoverage.dir/cmake_clean.cmake (8)
A build/CMakeFiles/ContinuousCoverage.dir/progress.make (1)
....

...
A build/Makefile (652)
A build/cmake_install.cmake (80)
A build/cmake_uninstall.cmake (27)
A build/install_manifest.txt (3)
A build/lib/libHiggs2zz.so (1)
A build/lib/libHiggs2zz.so.0.1 (1)
A build/lib/libHiggs2zz.so.0.1.0 (0)


Thanks!

**Comment by YonsiG** [comment]
> Please remove these files from git:
> A MarlinFastJet-00-02/lib/libMarlinFastJet.so (1)
> A MarlinFastJet-00-02/lib/libMarlinFastJet.so.0.2 (1)
> A MarlinFastJet-00-02/lib/libMarlinFastJet.so.0.2.0 (0)
> M MarlinFastJet-00-02/src/FastJetProcessor.cpp~ (0)
> All files under the "build" directory:
> A build/CMakeCache.txt (556)
> A build/CMakeFiles/CMakeCCompiler.cmake (49)
> A build/CMakeFiles/CMakeCXXCompiler.cmake (50)
> A build/CMakeFiles/CMakeDetermineCompilerABI_C.bin (0)
> A build/CMakeFiles/CMakeDetermineCompilerABI_CXX.bin (0)
> A build/CMakeFiles/CMakeDirectoryInformation.cmake (39)
> A build/CMakeFiles/CMakeOutput.log (239)
> A build/CMakeFiles/CMakeRuleHashes.txt (30)
> A build/CMakeFiles/CMakeSystem.cmake (15)
> A build/CMakeFiles/CompilerIdC/CMakeCCompilerId.c (229)
> A build/CMakeFiles/CompilerIdC/a.out (0)
> A build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp (215)
> A build/CMakeFiles/CompilerIdCXX/a.out (0)
> A build/CMakeFiles/Continuous.dir/DependInfo.cmake (13)
> A build/CMakeFiles/Continuous.dir/build.make (63)
> A build/CMakeFiles/Continuous.dir/cmake_clean.cmake (8)
> A build/CMakeFiles/Continuous.dir/progress.make (1)
> A build/CMakeFiles/ContinuousBuild.dir/DependInfo.cmake (13)
> A build/CMakeFiles/ContinuousBuild.dir/build.make (63)
> A build/CMakeFiles/ContinuousBuild.dir/cmake_clean.cmake (8)
> A build/CMakeFiles/ContinuousBuild.dir/progress.make (1)
> A build/CMakeFiles/ContinuousConfigure.dir/DependInfo.cmake (13)
> A build/CMakeFiles/ContinuousConfigure.dir/build.make (63)
> A build/CMakeFiles/ContinuousConfigure.dir/cmake_clean.cmake (8)
> A build/CMakeFiles/ContinuousConfigure.dir/progress.make (1)
> A build/CMakeFiles/ContinuousCoverage.dir/DependInfo.cmake (13)
> A build/CMakeFiles/ContinuousCoverage.dir/build.make (63)
> A build/CMakeFiles/ContinuousCoverage.dir/cmake_clean.cmake (8)
> A build/CMakeFiles/ContinuousCoverage.dir/progress.make (1)
> ....
> ...
> A build/Makefile (652)
> A build/cmake_install.cmake (80)
> A build/cmake_uninstall.cmake (27)
> A build/install_manifest.txt (3)
> A build/lib/libHiggs2zz.so (1)
> A build/lib/libHiggs2zz.so.0.1 (1)
> A build/lib/libHiggs2zz.so.0.1.0 (0)
> Thanks!

ok, I've put again

**Comment by xshi** [comment]
Thanks for the update. The files number decreased from 312 to 155! 

Please take  a look at the changed files again : 

https://github.com/cepc/hig2zz/pull/23/files

Make sure the binary files also cleaned: for example: 

root, lib/libHiggs2zz.so , etc

**Comment by YonsiG** [comment]
> Thanks for the update. The files number decreased from 312 to 155!
> 
> Please take a look at the changed files again :
> 
> https://github.com/cepc/hig2zz/pull/23/files
> 
> Make sure the binary files also cleaned: for example:
> 
> root, lib/libHiggs2zz.so , etc

I have removed the binary files, however, it seems there were old binary files in the master branch

**Comment by YonsiG** [comment]
Actually, there's more than 110 files unchanged at all. Like .txt files or others

**Comment by xshi** [comment]
Please notice the file type change also count: for example 100644 → 100755
Could you restore their previous type and push again? 
thanks!

**Comment by YonsiG** [comment]
I changed the file type and removed some binary files~

**Comment by YonsiG** [comment]
I think now the changes can be merged, if there are no other issues. Could you review it again?

**Comment by xshi** [comment]
Thanks  a lot! I can see only 27 files and looks good to me. 

@rkiuchi  Could you take a final look and merge it?

**Comment by rkiuchi** [comment]
For this pull request, I am also pretty fine.

**Pull request merged**
